updates to the network (#1061)
* security scan update

* thelio networking

* updates to security role

* network role updates

* updates to framework

* detect shell in autconf

* detect shell in autconf

diff --git a/ansible/collections/ansible_collections/lab/franklin/roles/security/templates/security_scan.sh.j2 b/ansible/collections/ansible_collections/lab/franklin/roles/security/templates/security_scan.sh.j2
--- a/ansible/collections/ansible_collections/lab/franklin/roles/security/templates/security_scan.sh.j2
+++ b/ansible/collections/ansible_collections/lab/franklin/roles/security/templates/security_scan.sh.j2
@@ -4,18 +4,52 @@
 #
 # SPDX-License-Identifier: GPL-3.0-or-later
 
-# updates
-lynis update info # grep for "Outdated" and update if needed
+# v0.1 16 FEB 2023
+# v0.2 21 DEC 2024 | added chkrootkit
 
-# During the security audit, Lynis attempts to assign two identifiers to the system.
-# They can be compared as fingerprints and can be used in other tools and to link data to an existing system.
+MYDATE=$(date +%Y%m%d)
+HOST=$(hostname -f)
+LOG_DIR="{{log_dir}}"
+REPORT_DIR="${LOG_DIR}/${HOST}"
+LYNIS_FILE="${LOG_DIR}/${HOST}/${MYDATE}-lynis.log"
+CHKROOT_FILE="${REPORT_DIR}/${MYDATE}-chkrootkit.log"
 
-# The first identifier is named hostid and has a length of 40 characters. The MAC address of
-# the system is typically used its data input. The second identifier is hostid2. It is 64 characters long and
-# typically uses a public SSH key a data input.
-lynis show hostids >> {{ lynis_dir }}/reports/hostids.txt
+if [ ! -d "${LOGDIR}" ]; then echo "Creating ${LOGDIR}" && mkdir ${LOGDIR}; fi
+if [ ! -d "${REPORT_DIR}" ]; then mkdir "${REPORT_DIR}"; fi
 
-cd {{ lynis_dir }}/reports && \
-  ksu -e lynis audit system --quick --auditor "franklin"
+function run_lynis() {
+  if [ -f "${LYNIS_FILE}" ]; then
+    echo "It looks like Lynis has already run once today. Skipping..."
+  else
+    command -v /usr/sbin/lynis >/dev/null 2>&1 ||
+      {
+        echo >&2 "lynis not found. Installing"
+        apt install -y lynis
+      }
+    /usr/sbin/lynis update info # grep for "Outdated" and update if needed
+    /usr/sbin/lynis show hostids >>${REPORT_DIR}/hostids.txt
+    /usr/sbin/lynis audit system --auditor "franklin" \
+      --log-file "${LYNIS_FILE}" --report-file "${REPORT_DIR}/${MYDATE}-lynis-report.dat"
+  fi
+}
 
 # scan the system for Dockerfiles and audit them
+function run_trivy() {
+  pass
+}
+
+function run_chkrootkit() {
+  if [ -f "${CHKROOT_FILE}" ]; then
+    echo "It looks like Chkrootkit has already run once today. Skipping..."
+  else
+    /usr/sbin/chkrootkit | tee "${CHKROOT_FILE}"
+  fi
+}
+
+function main() {
+  run_lynis
+  #run_trivy
+  run_chkrootkit
+}
+
+main "$@"
